CREATE DATABASE armorysafe; -- CRIA O BANCO DE DADOS 

USE armorysafe; -- SELECIONA O BANCO DA DADOS

CREATE TABLE cadastro( -- CRIA A TABELA DO CADASTRO DE MILITARES
idlog INT PRIMARY KEY AUTO_INCREMENT, -- PKEY
idmili CHAR(10) UNIQUE NOT NULL, -- Nº INTENTIDADE MILITAR (
psswrd VARCHAR(30) NOT NULL, -- SENHA DE LOGIN
dtcria DATETIME DEFAULT CURRENT_TIMESTAMP, -- DATA QUE FOI REALIZADO O CADASTRO
typ VARCHAR(30) NOT NULL -- TIPO DE USUARIO
CONSTRAINT chk_hirar CHECK(typ IN('Praça','Subalterno','Superior')),
orgmil VARCHAR(40) NOT NULL, -- ORGANIZAÇÃO MILITAR QUE É O MILITAR
regmili VARCHAR(30) NOT NULL, -- REGIÃO MILITAR DO USUARIO
sexo CHAR(1), -- SEXO DO USUARIO
CONSTRAINT chk_sex CHECK(sexo IN('F','M'))
);

CREATE TABLE munition( -- CRIA A TABELA DO PAIOL
idmun INT PRIMARY KEY AUTO_INCREMENT, -- PKEY IND
lote VARCHAR(10) NOT NULL, -- QUAL O LOTE DA MUNIÇÃO
loc VARCHAR(30) NOT NULL DEFAULT'Não Designado', -- EM QUAL PAIOL A MUNIÇAO ESTÁ LOCALIZADA
typ VARCHAR(10) NOT NULL, -- TIPO/CLASSIFICAÇÃO DA MUNIÇÃO
dtin DATETIME, -- DATA DE RECEBIMENTO
dtfab DATETIME, -- DATA DE FABRICAÇÃO
dtexm DATETIME, -- DATA DO ULTIMO EXAME REALIZADO
mark VARCHAR(10) DEFAULT 'TESTED' -- QUAIS TRABALHOS FORAM FEITOS NA MUNIÇÃO
CONSTRAINT chk_mark CHECK( mark IN('A','R','REP','INSP','PKD','DES','COND','US/T','TESTED','FAILED TEST')),
cond CHAR(2) DEFAULT'A1' -- CONDIÇÃO ATUAL DA MUNIÇÃO
CONSTRAINT chk_cond CHECK( cond IN('A1','A2','A3','B1','B2','B3','B4','C1','C2','C3','C4','C5','D1','D2','D3'))
);

CREATE TABLE umidade(
idum INT PRIMARY KEY AUTO_INCREMENT, -- INDENTIFICAÇÃO DO SENSOR
dtcap DATETIME, -- A DATA & HORARIO DA CAPTURA
qtum DECIMAL(4,2),  -- 12.34
locsen VARCHAR(30) -- EM QUAL PAIOL O SENSOR ESTÁ LOCALIZADO
);

DESC umidade;
DESC cadastro;
DESC munition;





